"""Initial schema: pgvector extension + all LegalOS tables.

This baseline revision materializes the current SQLAlchemy metadata; later
schema changes must be separate autogenerated revisions
(`alembic revision --autogenerate`), never edits to this file.

Revision ID: 0001
Revises:
Create Date: 2026-07-04

"""
from alembic import op

from app.db.base import Base
from app import models  # noqa: F401 — register all tables on Base.metadata

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    bind = op.get_bind()
    Base.metadata.create_all(bind=bind)


def downgrade() -> None:
    bind = op.get_bind()
    Base.metadata.drop_all(bind=bind)
